POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "pm27_test",
    "email": "push247_test@gmail.com",
    "password": "hehe"
}

###
GET http://localhost:3000/users/pm27
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJwbTI3X3Rlc3QiLCJlbWFpbCI6InB1c2hrYXJtMjdfdGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2NTc2MzIyNTcsImV4cCI6MTY1NzY2ODI1N30.8oM8IQJfCrBMr2oiY85emlHkraJ6rt58c5VaJSihP2c

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "pushkarm27_test@gmail.com",
    "password": "lasan"
}

###
GET http://localhost:3000/problems
Content-Type: application/json

###
POST http://localhost:3000/problems
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwbTI3IiwiZW1haWwiOiJwdXNoa2FybTI3QGdtYWlsLmNvbSIsImlhdCI6MTY1NzQ0MzU4NiwiZXhwIjoxNjU3NDc5NTg2fQ.2qCMzQ3T4_4NI9m2qiAXJQ_abcsJLf_-VSQT_SWsZ60

{
    "statement": "this is a problem",
    "test_input": "1 2 3 4",
    "test_output": "1 4 9 16"
}

###
GET http://localhost:3000/problems
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwbTI3IiwiZW1haWwiOiJwdXNoa2FybTI3QGdtYWlsLmNvbSIsImlhdCI6MTY1NzQ0MzU4NiwiZXhwIjoxNjU3NDc5NTg2fQ.2qCMzQ3T4_4NI9m2qiAXJQ_abcsJLf_-VSQT_SWsZ60

###
GET http://localhost:3000/problems/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwbTI3IiwiZW1haWwiOiJwdXNoa2FybTI3QGdtYWlsLmNvbSIsImlhdCI6MTY1NzQ0MzU4NiwiZXhwIjoxNjU3NDc5NTg2fQ.2qCMzQ3T4_4NI9m2qiAXJQ_abcsJLf_-VSQT_SWsZ60

###
GET http://localhost:3000/problems/1/tests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwbTI3IiwiZW1haWwiOiJwdXNoa2FybTI3QGdtYWlsLmNvbSIsImlhdCI6MTY1NzU3MTE2NywiZXhwIjoxNjU3NjA3MTY3fQ.meAq9JVN5P9WEN6PBFVpxvhcFoo6SGPhb7id0C1fZJs

###
GET http://localhost:3000/submissions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJwbTI3X3Rlc3QiLCJlbWFpbCI6InB1c2hrYXJtMjdfdGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2NTc2MTgyMTEsImV4cCI6MTY1NzY1NDIxMX0.YWxHrnk0i52pZq12HCkkh8drxMThZWDoM7uQ4-H2uyQ

###
GET http://localhost:3000/submissions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwbTI3IiwiZW1haWwiOiJwdXNoa2FybTI3QGdtYWlsLmNvbSIsImlhdCI6MTY1NzYyMTkxMCwiZXhwIjoxNjU3NjU3OTEwfQ.NbjfXjsjKH_RHu-a5Y7lwZYuT1CCM9JxHcOgpSzZ1jg

###
PUT http://localhost:3000/submissions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJwbTI3X3Rlc3QiLCJlbWFpbCI6InB1c2hrYXJtMjdfdGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2NTc2MjI2ODcsImV4cCI6MTY1NzY1ODY4N30.SS_BVKTw45EdaR3HoggjTDwiGMxXSVfDROxttXdjLJo

{
    "status": "AC"
}